### ISSUE TITLE
Add individual CAM description

### ISSUE THREAD

**Issue by crhea93** [crhea93/Valence#13]
Allow user to add a comment to be connected with individual CAMS.

**Comment by crhea93** [comment]
I suggest adding a "description" attribute to the "CAM" module.

**Comment by ChristianThibeault** [comment]
I think I should add the 'edit description' form where you can change the name of the CAM, saves space

**Comment by crhea93** [comment]
Sounds like a good idea!

**Comment by ChristianThibeault** [comment]
Descriptions are now available in "Edit CAM", and modifiable.

**BUT** you need to make the migrations in masters

**Comment by ChristianThibeault** [comment]
Description are now available in "Edit Cam" on the individual CAMs
