### ISSUE TITLE
Click on "project password": Sometimes nothing happens

### ISSUE THREAD

**Issue by Wilhelm-Gros** [crhea93/Valence#29]
For some testings, I created six accounts. It happened twice that I clicked on the checkbox "project password" and nothing happened (instead of opening the fields "project name" and "project password"). A simple untag and tagging again solved the problem. This issue is known to other partcipants as well. Maybe you have an idea?

![03a](https://user-images.githubusercontent.com/102617652/160679476-1d69b52d-ce03-44f9-8b9c-48cc2f79f017.png)

**Comment by crhea93** [comment]
@Wilhelm-Gros This is an annoying issue that is browser specific.... So unfortunately there is no nice way for me to fix this. I suggest adding a small message next to it telling participants to press it again incase it didn't work the first time. What do you think?

**Comment by Wilhelm-Gros** [comment]
In this case, this is better than nothing, I guess... What message do you want to leave (so I can translate it)?

**Comment by crhea93** [comment]
If the checkbox does not update please try again
@Wilhelm-Gros

**Comment by Wilhelm-Gros** [comment]
"If the checkbox does not update please try again" --> "Falls nichts passiert, Häkchen bitte nochmals setzen."

**Comment by crhea93** [comment]
Done :D
