### ISSUE TITLE
Downloading a non-existing predefined Map

### ISSUE THREAD

**Issue by Wilhelm-Gros** [crhea93/Valence#30]
Maybe there should be a notification if no predefined Map was entered. If there's no such Map, the browser tries to download something (which apparently is impossible) and the user is not aware of whats going on.

**Comment by crhea93** [comment]
@Wilhelm-Gros When does this happen?

**Comment by Wilhelm-Gros** [comment]
When clicking on
![01b](https://user-images.githubusercontent.com/102617652/161405731-0ead1223-578f-452a-aeb4-42c914a6b850.png)
:

**Comment by crhea93** [comment]
@ChristianThibeault Do you wanna tackle this? You should be able to  simply hide it if empty.

**Comment by crhea93** [comment]
![image](https://user-images.githubusercontent.com/34322936/161874603-e2bb52ca-ee7b-45f4-ac0e-d6951e08f373.png)
It doesn't show up now  if there isn't an initial map to download :D
