### ISSUE TITLE
1A priority Waterloo Updates

### ISSUE THREAD

**Issue by crhea93** [crhea93/Valence#32]
1A priority updates for the waterloo team. These are to be completed by April 1st, 2022.
- [x] Images should have 300 dpi resolution
- [x] Images should be able to be exported to grayscale
- [x] Increase the contrast between the outline of the shape and the inner area of the shape. Suggestion: Jinelle: I think we can achieve this by reducing the opacity percentage of the inner/background colour. Maybe go down another 5-10%?
- [x] Thicken all concept borders. Suggestion "The thicker can stay where they are. Expand the range of concept border thickness.
Jinelle: Let's try weak @ 6px, medium @ 11px, and strong at 17px (approximates)"
- [x] Make links darker: "Not the charcoal colour.
Jinelle: Let's go with #434343 instead"
- [x] Make links slightly smaller Jinelle: It looks like they are around 17px right now... can we go down to 14px?

**Comment by ChristianThibeault** [comment]
Adjusted all .svg files to satisfy opacity, line thickness and non-charcoal colour requests
