### ISSUE TITLE
German Things to Delete List

### ISSUE THREAD

**Issue by crhea93** [crhea93/Valence#6]
A small list of things to be deleted from the German version of the site:

- [x] Delete default thumbnail for CAMs (pic 1)
- [x] Delete all sidebar sections except for the “contributors” and the “Home/Dashboard”-button (the little house)
- [x] Delete the mailadress input field for participants, when they Login
- [x] Delete the “Settings” Button/Information after continuing without registration
- [x] Delete the picture option when registering as a researcher

**Comment by ChristianThibeault** [comment]
Replaced CAM.png with a white image
